"""Shared category taxonomies used by AI categorizer and Amazon importer."""

EXPENSE_CATEGORIES = [
    # Personal
    "Groceries & Food",
    "Restaurants & Dining",
    "Coffee & Beverages",
    "Gas & Fuel",
    "Auto & Transportation",
    "Parking & Tolls",
    "Airline & Travel",
    "Hotel & Lodging",
    "Entertainment & Recreation",
    "Shopping & Retail",
    "Clothing & Apparel",
    "Health & Medical",
    "Pharmacy & Prescriptions",
    "Dental & Vision",
    "Fitness & Gym",
    "Home & Garden",
    "Utilities",
    "Internet & Phone",
    "Streaming & Subscriptions",
    "Education & Tuition",
    "Childcare & Education",
    "Charitable Donations",
    "Insurance Premiums",
    "Personal Care & Spa",
    "Pet Care",
    "Gifts & Flowers",
    "Bank Fees & Interest",
    "ATM & Cash Withdrawal",
    "Credit Card Payment",
    "Tax Payments",
    # Business (Schedule C deductible)
    "Business — Advertising & Marketing",
    "Business — Software & Subscriptions",
    "Business — Office Supplies",
    "Business — Professional Services",
    "Business — Meals (50% deductible)",
    "Business — Travel & Transportation",
    "Business — Home Office",
    "Business — Phone & Internet (Business %)",
    "Business — Education & Training",
    "Business — Dues & Memberships",
    "Business — Legal & Accounting",
    "Business — Equipment & Technology",
    "Business — Other",
    # Income
    "W-2 Wages",
    "Dividend Income",
    "Interest Income",
    "Capital Gain",
    "Board / Director Income",
    "Payment / Refund",
    # Other
    "Transfer",
    "Unknown",
]

TAX_CATEGORIES = [
    "Schedule A — Medical Expenses",
    "Schedule A — State & Local Taxes (SALT)",
    "Schedule A — Mortgage Interest",
    "Schedule A — Charitable Contributions",
    "Schedule C — Advertising",
    "Schedule C — Car & Truck Expenses",
    "Schedule C — Commissions & Fees",
    "Schedule C — Contract Labor",
    "Schedule C — Depletion",
    "Schedule C — Depreciation",
    "Schedule C — Employee Benefit Programs",
    "Schedule C — Insurance (Business)",
    "Schedule C — Interest (Business)",
    "Schedule C — Legal & Professional",
    "Schedule C — Office Expense",
    "Schedule C — Pension & Profit Sharing",
    "Schedule C — Rent or Lease",
    "Schedule C — Repairs & Maintenance",
    "Schedule C — Supplies",
    "Schedule C — Taxes & Licenses",
    "Schedule C — Travel",
    "Schedule C — Meals (50%)",
    "Schedule C — Utilities",
    "Schedule C — Wages",
    "Schedule C — Other Expenses",
    "Form 2106 — Unreimbursed Employee Expenses",
    "Not Deductible",
    "Personal Expense",
]

AMAZON_CATEGORIES = [
    "Groceries & Food", "Electronics & Technology", "Clothing & Apparel",
    "Home & Garden", "Books & Media", "Health & Medical", "Baby & Kids",
    "Office Supplies", "Personal Care & Beauty", "Pet Care",
    "Sports & Fitness", "Automotive", "Toys & Games", "Kitchen & Dining",
    "Cleaning & Household", "Streaming & Digital", "Tools & Hardware",
    "Business — Office Supplies", "Business — Technology", "Business — Books & Training",
    "Business — Other", "Gift", "Unknown",
]
